In [1]:
import numpy as np

### 1. The basics

In [4]:
np.__version__

'1.20.1'

In [7]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [8]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

#### 1D Array

In [17]:
x = np.array([1,3.0])

In [18]:
x

array([1., 3.])

In [19]:
print(x)

[1. 3.]


In [20]:
type(x)

numpy.ndarray

In [21]:
x.ndim

1

In [22]:
x.shape

(2,)

In [23]:
x.size

2

In [24]:
x.dtype

dtype('float64')

#### 2D Array

In [27]:
x = np.array([[1,2],[-2,5]])
print(x)

[[ 1  2]
 [-2  5]]


In [29]:
x.ndim

2

In [30]:
x.shape

(2, 2)

In [31]:
x.dtype

dtype('int32')

#### 3D Array

In [36]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [37]:
x.ndim

3

In [39]:
x.shape

(3, 2, 3)

### Data types

In [41]:
A = np.array([1,2,3])
A.dtype

dtype('int32')

In [43]:
A = np.array([1,2,3], dtype='float')
A

array([1., 2., 3.])

In [44]:
A = np.array([1,2,3], dtype='complex')
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [46]:
A = np.array([True, False])
A.dtype

dtype('bool')

### Creating arrays

In [47]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [51]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [54]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(start=5, stop=50, step=10)

array([ 5, 15, 25, 35, 45])

In [58]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [60]:
A = np.arange(15)

In [61]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### Array operations

In [64]:
A = np.array([3,1,2,6])
B = np.array([3,1,5,3])
print(A)
print(B)

[3 1 2 6]
[3 1 5 3]


In [65]:
#np.add(A,B)
A+B

array([6, 2, 7, 9])

In [66]:
#np.subtract(A,B)
A-B

array([ 0,  0, -3,  3])

In [67]:
#np.multiply(A,B)
A*B

array([ 9,  1, 10, 18])

In [71]:
#np.divide(A,B)
A/B

array([1. , 1. , 0.4, 2. ])

In [72]:
A + 3

array([6, 4, 5, 9])

In [74]:
2 * A


array([ 6,  2,  4, 12])

In [80]:
X = np.array([[1,3],[1,2]])
Y = np.array([[5,2],[5,6]])
print(X)
print(Y)

[[1 3]
 [1 2]]
[[5 2]
 [5 6]]


In [81]:
X * Y 

array([[ 5,  6],
       [ 5, 12]])

In [82]:
np.dot(X,Y)

array([[20, 20],
       [15, 14]])

In [83]:
X.dot(Y)

array([[20, 20],
       [15, 14]])

In [84]:
Y.dot(X)

array([[ 7, 19],
       [11, 27]])

In [85]:
X @ Y

array([[20, 20],
       [15, 14]])

#### Generating pseudo-random numbers

In [87]:
np.random.seed(0)

In [91]:
np.random.randn(10,4)

array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 , -1.25279536,  0.77749036],
       [-1.61389785, -0.21274028, -0.89546656,  0.3869025 ]])

In [92]:
np.random.rand()

0.1965823616800535

In [93]:
np.random.rand(10,2)

array([[0.36872517, 0.82099323],
       [0.09710128, 0.83794491],
       [0.09609841, 0.97645947],
       [0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145]])

In [100]:
np.random.randint(low=10, high=101)

46

In [105]:
np.random.choice([4,2,1,4,11,5,321,64,32])

1

In [106]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [107]:
data = np.arae(10)

AttributeError: module 'numpy' has no attribute 'aragne'