In [2]:
import numpy as np

### 1. The basics

In [4]:
np.__version__

'1.20.1'

In [7]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [8]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

#### 1D Array

In [17]:
x = np.array([1,3.0])

In [18]:
x

array([1., 3.])

In [19]:
print(x)

[1. 3.]


In [20]:
type(x)

numpy.ndarray

In [21]:
x.ndim

1

In [22]:
x.shape

(2,)

In [23]:
x.size

2

In [24]:
x.dtype

dtype('float64')

#### 2D Array

In [27]:
x = np.array([[1,2],[-2,5]])
print(x)

[[ 1  2]
 [-2  5]]


In [29]:
x.ndim

2

In [30]:
x.shape

(2, 2)

In [31]:
x.dtype

dtype('int32')

#### 3D Array

In [36]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [37]:
x.ndim

3

In [39]:
x.shape

(3, 2, 3)

### Data types

In [41]:
A = np.array([1,2,3])
A.dtype

dtype('int32')

In [43]:
A = np.array([1,2,3], dtype='float')
A

array([1., 2., 3.])

In [44]:
A = np.array([1,2,3], dtype='complex')
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [46]:
A = np.array([True, False])
A.dtype

dtype('bool')

### Creating arrays

In [47]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [51]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [54]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(start=5, stop=50, step=10)

array([ 5, 15, 25, 35, 45])

In [58]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [60]:
A = np.arange(15)

In [61]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### Array operations

In [64]:
A = np.array([3,1,2,6])
B = np.array([3,1,5,3])
print(A)
print(B)

[3 1 2 6]
[3 1 5 3]


In [65]:
#np.add(A,B)
A+B

array([6, 2, 7, 9])

In [66]:
#np.subtract(A,B)
A-B

array([ 0,  0, -3,  3])

In [67]:
#np.multiply(A,B)
A*B

array([ 9,  1, 10, 18])

In [71]:
#np.divide(A,B)
A/B

array([1. , 1. , 0.4, 2. ])

In [72]:
A + 3

array([6, 4, 5, 9])

In [74]:
2 * A


array([ 6,  2,  4, 12])

In [80]:
X = np.array([[1,3],[1,2]])
Y = np.array([[5,2],[5,6]])
print(X)
print(Y)

[[1 3]
 [1 2]]
[[5 2]
 [5 6]]


In [81]:
X * Y 

array([[ 5,  6],
       [ 5, 12]])

In [82]:
np.dot(X,Y)

array([[20, 20],
       [15, 14]])

In [83]:
X.dot(Y)

array([[20, 20],
       [15, 14]])

In [84]:
Y.dot(X)

array([[ 7, 19],
       [11, 27]])

In [85]:
X @ Y

array([[20, 20],
       [15, 14]])

#### Generating pseudo-random numbers

In [87]:
np.random.seed(0)

In [91]:
np.random.randn(10,4)

array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 , -1.25279536,  0.77749036],
       [-1.61389785, -0.21274028, -0.89546656,  0.3869025 ]])

In [92]:
np.random.rand()

0.1965823616800535

In [93]:
np.random.rand(10,2)

array([[0.36872517, 0.82099323],
       [0.09710128, 0.83794491],
       [0.09609841, 0.97645947],
       [0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145]])

In [100]:
np.random.randint(low=10, high=101)

46

In [105]:
np.random.choice([4,2,1,4,11,5,321,64,32])

1

In [106]:
np.random.choice(['python', 'java', 'sql'])

'python'

#### The basics funtions

In [3]:
np.exp(1)

2.718281828459045

In [5]:
np.sqrt(9)

3.0

In [8]:
np.all([2,3,-1])

True

In [9]:
np.any([1,2,3])

True

In [10]:
bool(0)

False

In [12]:
bool(1.9421)

True

In [17]:
A = np.random.rand(5)
A

array([0.60836999, 0.69855418, 0.70929788, 0.46502685, 0.90307098])

In [18]:
np.argmax(A)

4

In [19]:
A[np.argmax(A)]

0.9030709823457924

In [21]:
np.argmin(A)

3

In [22]:
np.max(A)

0.9030709823457924

In [23]:
np.median(A)

0.698554180969249

In [24]:
np.std(A)

0.14300938952795772

In [25]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
A[-2]

18

In [27]:
A[-5:-1]

array([15, 16, 17, 18])

In [28]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
A[:,1]

array([ 1,  6, 11, 16])

In [34]:
A[1]

array([5, 6, 7, 8, 9])

In [35]:
A[3][4]

19

In [41]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [43]:
A[1,2] = 14

In [45]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#### Arrays interaction

In [46]:
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [47]:
for row in A:
    print(row[2])

2
14
12
17


In [48]:
for cell in A.flat:
    print(cell)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [49]:
A.shape

(4, 5)

In [50]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [51]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [57]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10,-1)

In [59]:
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [60]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [61]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [65]:
np.bitwise_and(A>-5, A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [66]:
A[np.bitwise_and(A > -5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [67]:
np.bitwise_or(A<-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### ALEGBRA LINIOWA

In [68]:
# Norma wektorowa, dugość wektora w R^2
#v = [v1 + v2]
#||v|| = pierwsiastek(v1^2 + v2^2)


In [75]:
v1 = np.array([10,10])
v1

array([10, 10])

In [76]:
np.linalg.norm(v1)

14.142135623730951

In [78]:
#Norma euklidesowa w R^n
#||v|| = pierwsiastek(v1^2+v2^2 +...+vn^2)

In [80]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

In [81]:
# odległość dwóch puntków na płaszczyźnie


In [82]:
P = np.array([3,0])
Q = np.array([0,4])

In [83]:
np.linalg.norm(P-Q)

5.0

In [84]:
P = np.array([3,0,1])
Q = np.array([0,4,2])
np.linalg.norm(P-Q)

5.0990195135927845

#### Matrix multiplication

In [5]:
X = np.array([[5,3],[3,9]])
Y = np.array([[1],[-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [7]:
Z = np.dot(X,Y)
Z

array([[ 2],
       [-6]])

In [8]:
Z.shape

(2, 1)

#### Determinant of the matrix

In [11]:
A = np.array([[2,4],[-1,3]])
round(np.linalg.det(A))

10

#### Matrix trace

In [12]:
np.trace(A)

5

#### Identity matrix

In [15]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#### Inverse matrix

In [16]:
A

array([[ 2,  4],
       [-1,  3]])

In [17]:
B = np.linalg.inv(A)

In [18]:
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [22]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

#### Transposed matrix

In [23]:
#Zamiana wierszy na kolumny i kolumny na wiersze

In [24]:
A

array([[ 2,  4],
       [-1,  3]])

In [25]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [26]:
A.T

array([[ 2, -1],
       [ 4,  3]])

#### System of equations

In [27]:
A=np.array([[2,4],[1,-1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [29]:
B = np.array([[10],[-1]])
print(B)

[[10]
 [-1]]


In [31]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

In [32]:
X

array([[1.],
       [2.]])

#### Statistical functions

In [33]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [34]:
np.sum(price, axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [35]:
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [36]:
np.max(price,axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

In [37]:
np.std(price,axis=0)

array([  0.1247,   0.2494,   0.2055,   0.411 , 408.2483])

In [38]:
np.mean(price,axis=0)

array([  12.3667,   13.0667,   11.9333,   12.6667, 1500.    ])

In [41]:
np.var(price,axis=0)

array([     0.0156,      0.0622,      0.0422,      0.1689, 166666.6667])

In [40]:
np.median(price,axis=0)

array([  12.4,   13. ,   11.9,   12.6, 1500. ])